[package]
name = "audiokeyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# alsa-sys = "*"
fltk = { version = "1.3.15", features = ["fltk-bundled", "use-ninja"]}
rodio = "0.15.0"
